/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 7.5 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n FIFO -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 11 -rp 1010 -data_width 16 -rdata_width 16 -num_rows 8192 -writemodeA NORMAL -writemodeB NORMAL -resetmode SYNC -cascade -1  */
/* Sun Apr 10 20:54:00 2022 */


`timescale 1 ns / 1 ps
module FIFO (DataInA, DataInB, AddressA, AddressB, ClockA, ClockB, 
    ClockEnA, ClockEnB, WrA, WrB, ResetA, ResetB, QA, QB)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] DataInA;
    input wire [15:0] DataInB;
    input wire [12:0] AddressA;
    input wire [12:0] AddressB;
    input wire ClockA;
    input wire ClockB;
    input wire ClockEnA;
    input wire ClockEnB;
    input wire WrA;
    input wire WrB;
    input wire ResetA;
    input wire ResetB;
    output wire [15:0] QA;
    output wire [15:0] QB;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_0_7
    (.DIA0(scuba_vlo), .DIA1(DataInA[1]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[0]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[1]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[0]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[0]), .DOA1(QA[1]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[0]), 
        .DOB1(QB[1]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_1_6
    (.DIA0(scuba_vlo), .DIA1(DataInA[3]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[2]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[3]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[2]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[2]), .DOA1(QA[3]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[2]), 
        .DOB1(QB[3]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_2_5
    (.DIA0(scuba_vlo), .DIA1(DataInA[5]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[4]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[5]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[4]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[4]), .DOA1(QA[5]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[4]), 
        .DOB1(QB[5]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_3_4
    (.DIA0(scuba_vlo), .DIA1(DataInA[7]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[6]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[7]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[6]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[6]), .DOA1(QA[7]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[6]), 
        .DOB1(QB[7]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_4_3
    (.DIA0(scuba_vlo), .DIA1(DataInA[9]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[8]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[9]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[8]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[8]), .DOA1(QA[9]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[8]), 
        .DOB1(QB[9]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_5_2
    (.DIA0(scuba_vlo), .DIA1(DataInA[11]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[10]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[11]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[10]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[10]), .DOA1(QA[11]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[10]), 
        .DOB1(QB[11]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_6_1
    (.DIA0(scuba_vlo), .DIA1(DataInA[13]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[12]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[13]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[12]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[12]), .DOA1(QA[13]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[12]), 
        .DOB1(QB[13]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    DP16KB
    #(
      .CSDECODE_B  ( 3'b000 ),
      .CSDECODE_A  ( 3'b000 ),
      .WRITEMODE_B ("NORMAL" ),
      .WRITEMODE_A ("NORMAL" ),
      .GSR         ("DISABLED" ),
      .RESETMODE   ("SYNC" ),
      .REGMODE_B   ("NOREG" ),
      .REGMODE_A   ("NOREG" ),
      .DATA_WIDTH_B(2 ),
      .DATA_WIDTH_A(2 )
    )
    FIFO_0_7_0
    (.DIA0(scuba_vlo), .DIA1(DataInA[15]), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(DataInA[14]), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(AddressA[0]), .ADA2(AddressA[1]), .ADA3(AddressA[2]), .ADA4(AddressA[3]), 
        .ADA5(AddressA[4]), .ADA6(AddressA[5]), .ADA7(AddressA[6]), .ADA8(AddressA[7]), 
        .ADA9(AddressA[8]), .ADA10(AddressA[9]), .ADA11(AddressA[10]), .ADA12(AddressA[11]), 
        .ADA13(AddressA[12]), .CEA(ClockEnA), .CLKA(ClockA), .WEA(WrA), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(ResetA), 
        .DIB0(scuba_vlo), .DIB1(DataInB[15]), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(DataInB[14]), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(AddressB[0]), 
        .ADB2(AddressB[1]), .ADB3(AddressB[2]), .ADB4(AddressB[3]), .ADB5(AddressB[4]), 
        .ADB6(AddressB[5]), .ADB7(AddressB[6]), .ADB8(AddressB[7]), .ADB9(AddressB[8]), 
        .ADB10(AddressB[9]), .ADB11(AddressB[10]), .ADB12(AddressB[11]), 
        .ADB13(AddressB[12]), .CEB(ClockEnB), .CLKB(ClockB), .WEB(WrB), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(ResetB), 
        .DOA0(QA[14]), .DOA1(QA[15]), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(QB[14]), 
        .DOB1(QB[15]), .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="NOREG" */
             /* synthesis REGMODE_A="NOREG" */
             /* synthesis DATA_WIDTH_B="2" */
             /* synthesis DATA_WIDTH_A="2" */;



    // exemplar begin
    // exemplar attribute FIFO_0_0_7 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_0_7 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_0_7 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_0_7 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_0_7 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_0_7 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_0_7 GSR DISABLED
    // exemplar attribute FIFO_0_0_7 RESETMODE SYNC
    // exemplar attribute FIFO_0_0_7 REGMODE_B NOREG
    // exemplar attribute FIFO_0_0_7 REGMODE_A NOREG
    // exemplar attribute FIFO_0_0_7 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_0_7 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_1_6 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_1_6 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_1_6 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_1_6 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_1_6 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_1_6 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_1_6 GSR DISABLED
    // exemplar attribute FIFO_0_1_6 RESETMODE SYNC
    // exemplar attribute FIFO_0_1_6 REGMODE_B NOREG
    // exemplar attribute FIFO_0_1_6 REGMODE_A NOREG
    // exemplar attribute FIFO_0_1_6 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_1_6 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_2_5 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_2_5 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_2_5 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_2_5 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_2_5 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_2_5 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_2_5 GSR DISABLED
    // exemplar attribute FIFO_0_2_5 RESETMODE SYNC
    // exemplar attribute FIFO_0_2_5 REGMODE_B NOREG
    // exemplar attribute FIFO_0_2_5 REGMODE_A NOREG
    // exemplar attribute FIFO_0_2_5 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_2_5 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_3_4 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_3_4 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_3_4 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_3_4 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_3_4 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_3_4 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_3_4 GSR DISABLED
    // exemplar attribute FIFO_0_3_4 RESETMODE SYNC
    // exemplar attribute FIFO_0_3_4 REGMODE_B NOREG
    // exemplar attribute FIFO_0_3_4 REGMODE_A NOREG
    // exemplar attribute FIFO_0_3_4 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_3_4 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_4_3 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_4_3 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_4_3 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_4_3 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_4_3 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_4_3 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_4_3 GSR DISABLED
    // exemplar attribute FIFO_0_4_3 RESETMODE SYNC
    // exemplar attribute FIFO_0_4_3 REGMODE_B NOREG
    // exemplar attribute FIFO_0_4_3 REGMODE_A NOREG
    // exemplar attribute FIFO_0_4_3 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_4_3 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_5_2 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_5_2 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_5_2 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_5_2 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_5_2 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_5_2 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_5_2 GSR DISABLED
    // exemplar attribute FIFO_0_5_2 RESETMODE SYNC
    // exemplar attribute FIFO_0_5_2 REGMODE_B NOREG
    // exemplar attribute FIFO_0_5_2 REGMODE_A NOREG
    // exemplar attribute FIFO_0_5_2 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_5_2 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_6_1 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_6_1 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_6_1 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_6_1 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_6_1 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_6_1 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_6_1 GSR DISABLED
    // exemplar attribute FIFO_0_6_1 RESETMODE SYNC
    // exemplar attribute FIFO_0_6_1 REGMODE_B NOREG
    // exemplar attribute FIFO_0_6_1 REGMODE_A NOREG
    // exemplar attribute FIFO_0_6_1 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_6_1 DATA_WIDTH_A 2
    // exemplar attribute FIFO_0_7_0 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute FIFO_0_7_0 MEM_INIT_FILE 
    // exemplar attribute FIFO_0_7_0 CSDECODE_B 0b000
    // exemplar attribute FIFO_0_7_0 CSDECODE_A 0b000
    // exemplar attribute FIFO_0_7_0 WRITEMODE_B NORMAL
    // exemplar attribute FIFO_0_7_0 WRITEMODE_A NORMAL
    // exemplar attribute FIFO_0_7_0 GSR DISABLED
    // exemplar attribute FIFO_0_7_0 RESETMODE SYNC
    // exemplar attribute FIFO_0_7_0 REGMODE_B NOREG
    // exemplar attribute FIFO_0_7_0 REGMODE_A NOREG
    // exemplar attribute FIFO_0_7_0 DATA_WIDTH_B 2
    // exemplar attribute FIFO_0_7_0 DATA_WIDTH_A 2
    // exemplar end

endmodule
