/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.4 */
/* Sat May 07 17:40:49 2022 */

/* parameterized module instance */
LogScaleLUT __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
